name: Build and Deploy Resume

on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install resume-cli
        run: npm install -g resume-cli

      - name: Install themes
        run: npm install

      - name: Create site
        run: |
          mkdir publish
          cp photo.jpeg publish/photo.jpeg
          resume export publish/index.html --theme=stackoverflow

      - name: Generate pdf resume
        if: startsWith(github.ref, 'refs/tags/')  # only run if triggered by a tag
        run: |
          mkdir artifact
          export RESUME_PUPPETEER_NO_SANDBOX=1
          resume export artifact/resume.pdf --theme=stackoverflow

      - name: Upload pdf resume as artifact
        if: startsWith(github.ref, 'refs/tags/')  # only run if triggered by a tag
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: artifact/resume.pdf

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: publish

  release:
    if: startsWith(github.ref, 'refs/tags/')  # only run if triggered by a tag
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Resume Artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: release

      - name: Rename resume
        run: mv release/resume.pdf release/Matthew-Macdonald-Resume-${{ github.ref_name }}.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/Matthew-Macdonald-Resume-${{ github.ref_name }}.pdf
          tag_name: ${{ github.ref_name }}
          release_name: "Resume ${{ github.ref_name }}"
          body: "Auto-generated resume from commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
